# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200408_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 22, 39, 40, 811990, tzinfo=utc)),
        ),
    ]
